print("Menu de Opções:")
print("1. Verificar saldo")
print("2. Realizar saque")
print("3. Realizar depósito")
print("4. Sair")
escolha = input("Escolha uma opção (1-4): ")
print("Você escolheu a opção:", escolha)