resultado1 = str(True)
print(f"True para str: {resultado1}, Tipo: {type(resultado1)}")
resultado2 = float(3)
print(f"3 para float: {resultado2}, Tipo: {type(resultado2)}")
resultado3 = str(3.8)
print(f"3.8 para str: {resultado3}, Tipo: {type(resultado3)}")
resultado4 = int(0.5)
print(f"0.5 para int: {resultado4}, Tipo: {type(resultado4)}")
resultado5 = int("4")
print(f'"4" para int: {resultado5}, Tipo: {type(resultado5)}')